# Generated by Django 5.1.6 on 2025-03-03 02:46

import booth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=50)),
                ('booth_name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[(None, ''), ('만해광장', '만해광장'), ('팔정도', '팔정도')], default='', max_length=30)),
                ('booth_num', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('club_logo', models.ImageField(blank=True, null=True, upload_to=booth.models.image_upload_path)),
                ('club_category', models.CharField(max_length=20)),
                ('club_description', models.TextField(blank=True, null=True)),
                ('booth_description', models.TextField(blank=True, null=True)),
                ('recruitment', models.CharField(blank=True, max_length=150, null=True)),
                ('apply_method', models.TextField()),
                ('insta_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, ''), ('수', '(수)'), ('목', '(목)')], default='', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoothImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=booth.models.image_upload_path)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='booth.booth')),
            ],
        ),
        migrations.AddField(
            model_name='booth',
            name='day',
            field=models.ManyToManyField(to='booth.day'),
        ),
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_truck_name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[(None, ''), ('만해광장', '만해광장'), ('팔정도', '팔정도')], default='', max_length=30)),
                ('food_truck_num', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('food_truck_description', models.CharField(max_length=400)),
                ('insta_url', models.URLField(blank=True, null=True)),
                ('day', models.ManyToManyField(to='booth.day')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruckImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=booth.models.image_upload_path)),
                ('food_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='booth.foodtruck')),
            ],
        ),
    ]
