# Generated by Django 5.1.6 on 2025-02-18 08:09

import booth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_truck_name', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[(None, ''), ('(수)', '(수)'), ('(목)', '(목)')], default='', max_length=20)),
                ('location', models.CharField(choices=[(None, ''), ('만해광장', '만해광장'), ('팔정도', '팔정도')], default='', max_length=30)),
                ('food_truck_num', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('food_truck_discription', models.CharField(max_length=400)),
                ('insta_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTruckImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=booth.models.image_upload_path)),
                ('food_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='booth.foodtruck')),
            ],
        ),
    ]
