# Generated by Django 5.1.6 on 2025-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_foodtruck_foodtruckimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='insta_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
