# Generated by Django 5.1.6 on 2025-02-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_alter_booth_apply_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
