# Generated by Django 5.1.6 on 2025-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_alter_foodtruck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtruck',
            name='booth_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
