# Generated by Django 5.1.6 on 2025-02-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_alter_booth_insta_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(None, ''), ('수', '(수)'), ('목', '(목)')], default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='booth',
            name='day',
        ),
        migrations.RemoveField(
            model_name='foodtruck',
            name='day',
        ),
        migrations.AddField(
            model_name='booth',
            name='day',
            field=models.ManyToManyField(to='booth.day'),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='day',
            field=models.ManyToManyField(to='booth.day'),
        ),
    ]
