# Generated by Django 5.1.6 on 2025-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_remove_foodtruck_insta_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
