# Generated by Django 5.1.6 on 2025-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_day_remove_booth_day_remove_foodtruck_day_booth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[(None, ''), ('수', '(수)'), ('목', '(목)')], default='', max_length=10, unique=True),
        ),
    ]
