# Generated by Django 5.1.6 on 2025-02-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_remove_booth_day_remove_foodtruck_day_day_booths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='booths',
        ),
        migrations.AddField(
            model_name='booth',
            name='day',
            field=models.ManyToManyField(to='booth.day'),
        ),
        migrations.AddField(
            model_name='foodtruck',
            name='day',
            field=models.ManyToManyField(to='booth.day'),
        ),
    ]
