# Generated by Django 5.1.6 on 2025-02-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[(None, ''), ('(수)', '(수)'), ('(목)', '(목)')], default='', max_length=30)),
                ('location', models.CharField(choices=[(None, ''), ('만해광장', '만해광장'), ('팔정도', '팔정도')], default='', max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('insta_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='performance.performance')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='performance.performance')),
            ],
        ),
    ]
