# Generated by Django 5.1.6 on 2025-02-25 13:40

import django.db.models.deletion
import performance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=performance.models.image_upload_path)),
                ('category', models.CharField(max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('insta_url', models.CharField(max_length=50)),
                ('day', models.ManyToManyField(to='booth.day')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='performance.performance')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='performance.performance')),
            ],
        ),
    ]
