# Generated by Django 5.1.6 on 2025-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_alter_day_name'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='day',
        ),
        migrations.AddField(
            model_name='performance',
            name='day',
            field=models.ManyToManyField(to='booth.day'),
        ),
    ]
