# Generated by Django 5.1.6 on 2025-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='insta_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.TextField(),
        ),
    ]
