# Generated by Django 5.1.6 on 2025-02-22 19:32

import performance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_remove_performance_day_performance_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='location',
        ),
        migrations.AddField(
            model_name='performance',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=performance.models.image_upload_path),
        ),
    ]
